services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: angular-node-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/angular-node-app
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-node-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:8
    container_name: angular-node-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        ["CMD-SHELL", 'mongosh --quiet --eval "db.adminCommand(''ping'').ok"']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_data:
